### ISSUE TITLE
Crashes with guzzlehttp/psr7 1.5.2 version

### ISSUE THREAD

**Issue by kordos** [mcustiel/phiremock-codeception-extension#28]
It is crashing with guzzlehttp/psr7 in version 1.5.2. It works correctly with 1.4.2 version.

Here are logs: 

```
[2019-01-29 11:54:48] stdoutLogger.INFO: Starting Phiremock... [] []
[2019-01-29 11:54:49] stdoutLogger.INFO: Loading expectations from directory /var/www/html/tests/api/config/Phiremock/expectations/ [] []
[2019-01-29 11:54:51] stdoutLogger.INFO: Phiremock http server listening on 127.0.0.1:18080 [] []

Fatal error: Uncaught InvalidArgumentException: Invalid message: Missing header delimiter in /var/www/html/vendor/guzzlehttp/psr7/src/functions.php on line 772

InvalidArgumentException: Invalid message: Missing header delimiter in /var/www/html/vendor/guzzlehttp/psr7/src/functions.php on line 772

Call Stack:
    0.0011     352944   1. {main}() /var/www/html/vendor/mcustiel/phiremock/bin/phiremock:0
    0.0100     373752   2. require('/var/www/html/vendor/mcustiel/phiremock/bin/phiremock.php') /var/www/html/vendor/mcustiel/phiremock/bin/phiremock:4
    3.5899    3006272   3. Mcustiel\Phiremock\Server\Http\Implementation\ReactPhpServer->listen() /var/www/html/vendor/mcustiel/phiremock/bin/phiremock.php:65
    3.6188    3021176   4. React\EventLoop\StreamSelectLoop->run() /var/www/html/vendor/mcustiel/phiremock/src/Server/Http/Implementation/ReactPhpServer.php:80
   11.0360    3101592   5. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php:205
   11.0360    3102072   6. call_user_func:{/var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php:236}() /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php:236
   11.0360    3102072   7. React\Socket\Connection->handleData() /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php:236
   11.0360    3172104   8. React\Socket\Connection->emit() /var/www/html/vendor/react/stream/src/Stream.php:173
   11.0360    3172104   9. React\Http\RequestHeaderParser->feed() /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:70
   11.0360    3172424  10. React\Http\RequestHeaderParser->parseRequest() /var/www/html/vendor/react/http/src/RequestHeaderParser.php:28
   11.0361    3172776  11. GuzzleHttp\Psr7\parse_request() /var/www/html/vendor/react/http/src/RequestHeaderParser.php:39
   11.0361    3172776  12. GuzzleHttp\Psr7\_parse_message() /var/www/html/vendor/guzzlehttp/psr7/src/functions.php:469

[2019-01-29 11:54:59] stdoutLogger.INFO: Stopping Phiremock... [] []
[2019-01-29 11:54:59] stdoutLogger.INFO: Bye bye [] []
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid message: Missing header delimiter in /var/www/html/vendor/guzzlehttp/psr7/src/functions.php:772
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/psr7/src/functions.php(469): GuzzleHttp\Psr7\_parse_message('GET /v1/job-app...')
#1 /var/www/html/vendor/react/http/src/RequestHeaderParser.php(39): GuzzleHttp\Psr7\parse_request('GET /v1/job-app...')
#2 /var/www/html/vendor/react/http/src/RequestHeaderParser.php(28): React\Http\RequestHeaderParser->parseRequest('GET /v1/job-app...')
#3 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): React\Http\RequestHeaderParser->feed('GET /v1/job-app...', Object(React\Socket\Connection))
#4 /var/www/html/vendor/react/stream/src/Stream.php(173): Evenement\EventEmitter->emit('data', Array)
#5 [internal function]: React\Stream\Stream->handleData(Resource id #242, Object(React\EventLoop\StreamSelectLoop))
#6 /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php(236): call_user_func(Array, Resource id in /var/www/html/vendor/guzzlehttp/psr7/src/functions.php on line 772
```

Please fix issue.
Regards,
kordos

**Comment by mcustiel** [comment]
I can not reproduce it. 
Could you check that the http response from your api is correct? As far as the exception says, the response can not be parsed because the header delimiter is missing.
